Algoritmo "EX-MESA02"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Declarações das variáveis
     x, y, i : inteiro

Inicio
// Declando as variáveis
   x <- 0
   y <- 0

// Iniciando o Para

    para i de 1 ate 4 faca
         y <- i - 1
         x <- i * 10
    escreval(x, y, "-", i)
    
    fimpara


Fimalgoritmo