Algoritmo "EX-tabuada"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Declarações das variáveis
     N, i : inteiro

Inicio
// Solicitando os dados de entrada:
   escreval("Deseja a tabuada para qual valor?: ")
   leia(N)


// Iniciando o Para

    para i de 1 ate 10 faca

         escreval(N, " * ", i, " = ", N * i)
         
    
    fimpara


Fimalgoritmo