Algoritmo "processamento-dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2025
Var
// Declarando variáveis
   x, y : inteiro


Inicio
// Informando valores das varíaveis
      x <-5
      y <-2 * x
      
      
// Imprimindo valores

      escreval(x)
      escreval(y)

Fimalgoritmo