Algoritmo "usando_nome_Maria"

Var
// Declarando as váriaveis
   idade : inteiro
   salario : real
   nome : caractere


Inicio
// Usada para receber os valores:
   idade <- 32
   salario <- 3.152
   nome <- "Thalita"
   
// Ensinando escrever de forma de sáida
   escreval("A Colaboradora ",nome, ". Sua idade é de:",idade," ganha", salario:8:2)
   escreval


// Pular uma linha de escrita
   escreval("Bom dia")
   escreval
   escreval("Boa noite")

Fimalgoritmo