Algoritmo "Ex-ConsumoCarro"

Var
// Declarações das variáveis
   distancia : inteiro
   combustivel, gasto : real


Inicio
// escrevendo
   escreva("Qual a distancia percorrida em KM: ")
   leia(distancia)
   escreva("Quantidade de combustível gasto:  ")
   leia(combustivel)
   
//Calculando:
   gasto <- distancia / combustivel
   
// Declanado

   escreval("A média é de: ", gasto:8:3)


Fimalgoritmo